e--project/Models/ErrorViewModel.cs
namespace e__project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

e--project/Controllers/HomeController.cs
using e__project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace e__project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

e--project/Controllers/adminController.cs
using Microsoft.AspNetCore.Mvc;

namespace e__project.Controllers
{
    public class adminController : Controller
    {
        
		public IActionResult Dashboard()
		{
			return View();
		}
        public IActionResult AuctionManagement()
        {
            return View();
        }
       

    }
}

e--project/Controllers/userController.cs
using Microsoft.AspNetCore.Mvc;

namespace e__project.Controllers
{
    public class userController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

		public IActionResult IndexCar()
		{
			return View();
		}
		public IActionResult Dashboard()
		{
			return View();
		}
		public IActionResult IndexLand()
		{
			return View();
		}

		public IActionResult Auction()
		{
			return View();
		}

		public IActionResult AuctionDetails()
		{
			return View();
		}

		public IActionResult About()
		{
			return View();
		}

		public IActionResult Winner()
		{
			return View();
		}

		public IActionResult Login()
		{
			return View();
		}

		public IActionResult Register()
		{
			return View();
		}

		public IActionResult Faq()
		{
			return View();
		}

		public IActionResult PrivacyPolicy()
		{
			return View();
		}

		public IActionResult Error()
		{
			return View();
		}

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult BlogStandard()
        {
            return View();
        }

        public IActionResult BlogDetails()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
    }
}

e--project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

e--project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - Online Auction</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
@*     <link rel="stylesheet" href="~/e__project.styles.css" asp-append-version="true" />
 *@
    <!-- Custom fonts for this template-->
    <link href="~/assets/fontawesome-free/css/all.min.css" rel="stylesheet" />
   

    <!-- Custom styles for this template-->
    <link href="~/assets/css/sb-admin-2.min.css" rel="stylesheet" />
</head>
<body>
   @*  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">e__project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*   <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - e__project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/assets/js/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/assets/js/sb-admin-2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

e--project/Views/Shared/headfoot.cshtml
<!doctype html>
<html lang="en">


<head>
<title>Bid Spirit</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" href="~/assets/images/favicon.png" type="image/gif" sizes="20x20">

<link rel="stylesheet" href="~/assets/css/swiper-bundle.min.css">

<link rel="stylesheet" href="~/assets/css/boxicons.min.css">

<link rel="stylesheet" href="~/assets/css/bootstrap-icons.css">

<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="~/assets/css/magnific-popup.css">

<link rel="stylesheet" href="~/assets/css/style.css">
<link rel="stylesheet" href="~/assets/css/responsive.css">
</head>
<body>

<div class="preloader">
<div class="loader">
<span></span>
<span></span>
<span></span>
<span></span>
</div>
</div>
<div class="mobile-search">
<div class="container">
<div class="row">
<div class="col-11">
<label>What are you lookking for?</label>
<input type="text" placeholder="Search Products, Category, Brand">
</div>
<div class="col-1 d-flex justify-content-end align-items-center">
<div class="search-cross-btn">

<i class="bi bi-x"></i>
</div>
</div>
</div>
</div>
</div>

<div class="menu-toggle-btn-full-shape">
<div class="menu-toggle-wrap bg-white">
<div class="sidebar-top-area d-flex justify-content-between align-items-center">
<div class="cross-icon">
<i class="bx bx-x"></i>
</div>
<div class="sidebar-logo">
<a href="index.html"><img src="~/assets/images/icon/sidebar-logo.png" alt></a>
</div>
</div>
<div class="sidebar-body">
<h5>Our Social Site</h5>
<ul class="sidebar-social">
<li><a href="https://www.facebook.com/"><i class="bx bxl-facebook"></i><span>facebook.com/egenstheme</span></a></li>
<li><a href="https://twitter.com/"><i class="bx bxl-twitter"></i><span>twitter.com/egenstheme/</span></a></li>
<li><a href="https://www.instagram.com/"><i class="bx bxl-instagram"></i><span>instagram.com/egenstheme/</span></a></li>
<li><a href="https://www.pinterest.com/"><i class="bx bxl-pinterest-alt"></i><span>pinterest.com/egenstheme/</span></a></li>
</ul>
</div>
<div class="sidebar-bottom">
<p>Need Any Help? Please Mail Us!</p>
<a href="https://demo-egenslab.b-cdn.net/cdn-cgi/l/email-protection#8fe6e1e9e0cfcae8eae1fcfbe7eae2eaa1ece0e2"><span><i class="bx bx-envelope"></i><span class="__cf_email__" data-cfemail="5e373038311e3b393b302d2a363b333b703d3133">[email&#160;protected]</span></span></a>
</div>
</div>
<div class="sidebar-bottom-icon">
<svg width="40" height="41" viewBox="0 0 40 41" fill="none" xmlns="http://www.w3.org/2000/svg">
<mask id="mask0_1687_55" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="40" height="41">
<rect width="39.8116" height="41" fill="#C4C4C4" />
</mask>
<g mask="url(#mask0_1687_55)">
<path d="M30.6961 2.43256L1.93437 23.5151C0.104333 24.8566 -0.246827 27.4996 1.15152 29.4073L16.3665 50.1642C17.7648 52.0719 20.391 52.5325 22.221 51.1911L50.9828 30.1085C52.8128 28.7671 53.164 26.1241 51.7657 24.2164L36.5507 3.45945C35.1523 1.55176 32.5262 1.09113 30.6961 2.43256ZM32.3867 4.73888C32.537 4.62871 32.7038 4.55641 32.8761 4.51736L27.8759 28.7454L3.26629 26.2216C3.35545 26.0691 3.47455 25.9317 3.62484 25.8215L32.3867 4.73888ZM49.2922 27.8021L20.5304 48.8847C19.9201 49.3321 19.0453 49.1787 18.5789 48.5424L4.37018 29.1583L28.9084 31.6743C29.2548 31.7094 29.5815 31.6137 29.8397 31.4245C30.0979 31.2352 30.2876 30.9525 30.3582 30.6116L35.3445 6.45391L49.5532 25.8381C50.0195 26.4744 49.9026 27.3547 49.2922 27.8021Z" />
</g>
</svg>
</div>
</div>


<header>
<div class="header-area header-style-one px-md-5">
<div class="container-fluid">
<div class="row">
<div class="col-xl-2 align-items-center d-xl-flex d-lg-block">
<div class="nav-logo d-flex justify-content-between align-items-center">
<a href="@Url.Action("Index","user")"><img src="~/assets/images/logo.png" alt="logo"></a>
<div class="d-flex align-items-center gap-4">
<ul class="nav-actions nav-inner-actions d-flex d-xl-none">
<li class="search-btn"><i class="bi bi-search"></i></li>
<li class="header-account me-0 position-relative">
<a href="login.html" id="dropdownMenu4" data-bs-toggle="dropdown">
<i class="bi bi-person-fill"></i>
</a>
<ul class="dropdown-menu account-list-mobile" aria-labelledby="dropdownMenu4">
<li class="dropdown-item"><a href="login.html">My account</a></li>
<li class="dropdown-item"><a href="register.html">Settings</a></li>
<li class="dropdown-item"><a href="login.html">Login</a></li>
<li class="dropdown-item mb-0"><a href="register.html">Register</a></li>
</ul>
</li>
</ul>
<div class="mobile-menu d-flex ">
<a href="javascript:void(0)" class="hamburger d-block d-xl-none">
<span class="h-top"></span>
<span class="h-middle"></span>
<span class="h-bottom"></span>
</a>
</div>
</div>
</div>
</div>
<div class="col-xl-5">
<nav class="main-nav">
<div class="inner-logo d-xl-none text-center mt-4">
<a href="#"><img src="~/assets/images/logo-dark.png" alt></a>
</div>
<ul>
<li class="has-child-menu">
<a href="javascript:void(0)">Home</a>
<i class="fl flaticon-plus">+</i>
<ul class="sub-menu">
<li><a href="@Url.Action("Index","user")">Home Accessories </a></li>
<li><a href="@Url.Action("IndexCar","user")">Home Car</a></li>
<li><a href="@Url.Action("IndexLand","user")">Home Land</a></li>
</ul>
</li>
<li class="has-child-menu">
<a href="javascript:void(0)">Auction</a>
<i class="fl flaticon-plus">+</i>
<ul class="sub-menu">
<li><a href="@Url.Action("Auction","user")">auction</a></li>
<li><a href="@Url.Action("AuctionDetails","user")">auction details</a></li>
</ul>
</li>
<li class="has-child-menu">
<a href="javascript:void(0)">Pages</a>
<i class="fl flaticon-plus">+</i>
<ul class="sub-menu">
										<li><a href="@Url.Action("About","user")">about</a></li>
										<li><a href="@Url.Action("Winner","user")">winner</a></li>
										<li><a href="@Url.Action("Login","user")">login</a></li>
										<li><a href="@Url.Action("Register","user")">register</a></li>
										<li><a href="@Url.Action("Faq","user")">faq</a></li>
										<li><a href="@Url.Action("PrivacyPolicy","user")">Privacy Policy</a></li>
										<li><a href="@Url.Action("Error","user")">Error</a></li>
</ul>
</li>
								<li class="has-child-menu">
									<a href="javascript:void(0)">Blog</a>
									<i class="fl flaticon-plus">+</i>
									<ul class="sub-menu">
										<li><a href="@Url.Action("Blog","user")">Blog</a></li>
										<li><a href="@Url.Action("BlogStandard","user")">Blog Standard</a></li>
										<li><a href="@Url.Action("BlogDetails","user")">Blog Details</a></li>
									</ul>
									</li>
<li><a href="@Url.Action("Contact","user")">contact</a></li>

								<li><a href="@Url.Action("Login","user")" class="alpha-btn-md">Admin Login</a></li>
								

</ul>
						
<div class="contact-mail inner-contact-mail mt-5 d-block d-xl-none">
<span>Message Us</span>
<a href="https://demo-egenslab.b-cdn.net/cdn-cgi/l/email-protection#dfacaaafafb0adab9fbaa7beb2afb3baf1bcb0b2"><span class="__cf_email__" data-cfemail="05767075756a777145607d64687569602b666a68">[email&#160;protected]</span></a>
</div>
</nav>
</div>
<div class="col-xl-5 d-xl-flex align-items-center justify-content-end d-none">
<div class="nav-right d-flex align-items-center">
<form action="#" id="header_searchbar" class="d-xxl-block d-none">
<div class="nav-searchbar"><input type="text" placeholder="Search your items"></div>
</form>
<div class="nav-actions d-flex align-items-center">
<ul class="d-flex">
<li class="search-btn d-block d-xxl-none"><i class="bi bi-search"></i></li>
<li class="header-account me-0 position-relative">
<a id="dropdownMenu2" data-bs-toggle="dropdown">
<i class="bi bi-person-fill"></i>
</a>
<ul class="dropdown-menu account-list" aria-labelledby="dropdownMenu2">
<li class="dropdown-item"><a href="login.html">My account</a></li>
<li class="dropdown-item"><a href="register.html">Settings</a></li>
<li class="dropdown-item"><a href="login.html">Login</a></li>
<li class="dropdown-item"><a href="register.html">Register</a></li>
</ul>
</li>
<li></li>
<li class="menu-sidebar-btn"><i class="bi bi-list"></i></li>
</ul>
<div class="contact-mail">
<span>Message Us</span>
<a href="https://demo-egenslab.b-cdn.net/cdn-cgi/l/email-protection#572422272738252317322f363a273b327934383a"><span class="__cf_email__" data-cfemail="9be8eeebebf4e9efdbfee3faf6ebf7feb5f8f4f6">[email&#160;protected]</span></a>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</header>

@RenderBody()



<footer class="footer-area footer-style-one">
<div class="container">
<div class="footer-main">
<div class="row gy-5">
<div class="col-lg-4">
<div class="footer-widget">
<form action="#" id="subscribe_form">
<h3 class="form-title">subscribe us</h3>
<div class="form-wrap d-flex align-items-center">
<input type="email" placeholder="Enter Your Email">
<button type="submit">Send</button>
</div>
</form>
<div class="footer-contact-links">
<div class="contact-option">
<div class="icon">
<i class="bi bi-telephone-plus"></i>
</div>
<div class="link">
<a href="tel:8801761111456">+880 176 1111 456</a>
</div>
</div>
<div class="contact-option">
<div class="icon">
<i class="bi bi-envelope"></i>
</div>
<div class="link">
<a href="info%40example.html"><span class="__cf_email__" data-cfemail="8ce5e2eae3cce9f4ede1fce0e9a2efe3e1">[email&#160;protected]</span></a>
</div>
</div>
<div class="contact-option">
<div class="icon">
<i class="bi bi-geo-alt"></i>
</div>
<div class="link">
<a href="tel:8801761111456">168/170, Avenue 01,xyz, Bangladesh</a>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="row gy-5">
<div class="col-md-6 col-sm-6 d-flex justify-content-lg-center">
<div class="footer-widget">
<h5 class="widget-title">Quick Links</h5>
<ul class="widget-links">
<li><a href="login.html">My Account</a></li>
<li><a href="about.html">Affiliate Program</a></li>
<li><a href="contact.html">Lawyer Consulting</a></li>
<li><a href="#">Sorteo Locemses</a></li>
<li><a href="privacy.html">Privacey Policy</a></li>
<li><a href="#">Term & Condition</a></li>
</ul>
</div>
</div>
<div class="col-md-6 col-sm-6 d-flex justify-content-lg-center">
<div class="footer-widget">
<h5 class="widget-title">Help Center</h5>
<ul class="widget-links">
<li><a href="contact.html">Help Center</a></li>
<li><a href="faq.html">FAQ</a></li>
<li><a href="#">Borrow</a></li>
<li><a href="contact.html">License Agreement</a></li>
<li><a href="auction.html">Sell your Product</a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="footer-widget text-center text-lg-start">
<div class="footer-disc">
<a href="index.html"><img src="~/assets/images/logo.png" alt></a>
<p>Duis luctus risus ut velit aliquam, sed fringilla odio gravida. In vitae sagittis neque, eget vestibulum enim. Pellentesque ante odio.</p>
</div>
<ul class="footer-social-links justify-content-center justify-content-lg-start">
<li><a href="https://www.facebook.com/"><i class="bx bxl-facebook"></i></a></li>
<li><a href="https://twitter.com/"><i class="bx bxl-twitter"></i></a></li>
<li><a href="https://www.pinterest.com/"><i class="bx bxl-pinterest"></i></a></li>
<li><a href="https://www.instagram.com/"><i class="bx bxl-instagram"></i></a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="copyright row align-items-center">
<div class="col-lg-6 col-md-6 order-1 order-md-0 text-center text-md-start mt-3 mt-md-0">
<p>Copyright 2022 <a href="#">Bidgen</a> | Design By <a href="https://www.egenslab.com/">Egens Theme</a></p>
</div>
<div class="col-lg-6 col-md-6 order-0 order-md-1">
<div class="acceptable-cards float-lg-end text-center text-md-start">
<img src="~/assets/images/icon/payment-cards.png" alt class="img-fluid">
</div>
</div>
</div>
</div>
</footer>


<script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="~/assets/js/jquery-3.6.0.min.js"></script>
	<script src="~/assets/js/jquery-3.6.0.min.js"></script>
<script src="~/assets/js/swiper-bundle.min.js"></script>
<script src="~/assets/js/jquery.nice-select.js"></script>
<script src="~/assets/js/jquery.magnific-popup.min.js"></script>

<script src="~/assets/js/main.js"></script>


</body>




</html>

e--project/Views/user/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/headfoot.cshtml";
}

<div class="breadcrumb breadcrumb-style-one mb-0 ">
    <div class="container">
        <div class="col-lg-12 text-center">
            <h1 class="breadcrumb-title">Contact Us</h1>
            <ul class="d-flex justify-content-center breadcrumb-items">
                <li class="breadcrumb-item"><i class="bi bi-house-door"></i> <a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Contact Us</li>
            </ul>
        </div>
    </div>
</div>


<div class="contact-wrapper  mt-110">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-header mx-auto text-center">
                    <h3>Any Asking To The Officers?</h3>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-5">
                <div class="contact-box-wrap">
                    <h4>Contact Us</h4>
                    <div class="single-contact-box">
                        <h6>Let’s Talk</h6>
                        <a href="https://demo-egenslab.b-cdn.net/cdn-cgi/l/email-protection#8ce5e2eae3cce9f4ede1fce0e9a2efe3e1" class="mail"><span class="__cf_email__" data-cfemail="ed84838b82ad88958c809d8188c38e8280">[email&#160;protected]</span></a> <a href="https://demo-egenslab.b-cdn.net/cdn-cgi/l/email-protection#e5969095958a9791a5809d8488958980cb868a88" class="mail"><span class="__cf_email__" data-cfemail="c5b6b0b5b5aab7b185a0bda4a8b5a9a0eba6aaa8">[email&#160;protected]</span></a>
                        <a href="tel:8801761111456" class="phone">+88 0176 1111 456</a>
                    </div>
                    <div class="single-contact-box">
                        <h6>Loacation.</h6>
                        <a href="#" class="location">168/170, Ave 01, Streets Suite 66xyz, Bangladesh</a>
                    </div>
                    <div class="single-contact-box">
                        <h6>Social Site Link</h6>
                        <a href="#" class="weblink">Facebook: https://www.facebook.com/egenstheme</a>
                        <a href="#" class="weblink">Twitter: https://www.twitter.com/egenstheme</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 mt-5 mt-lg-0">
                <div class="contact-form">
                    <h4>Questions or Comments?</h4>
                    <form action="#" id="contact_form" method="post">
                        <div class="contact-input-group">
                            <label for="first-Name">Full Name</label>
                            <input type="text" id="first-Name" placeholder="Full Name">
                        </div>
                        <div class="contact-input-group">
                            <label for="email">Email</label>
                            <input type="text" id="email" placeholder="Enter Your Email">
                        </div>
                        <div class="contact-input-group">
                            <label for="email">Message</label>
<textarea id="massege" cols="30" rows="7" placeholder="Type your Message"></textarea>
                        </div>
                        <div class="contact-input-group mt-0">
                            <button type="submit" class="submit-btn">Submit Comment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

e--project/Views/user/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/headfoot.cshtml";
}

<div class="breadcrumb breadcrumb-style-one mb-0 ">
<div class="container">
<div class="col-lg-12 text-center">
<h1 class="breadcrumb-title">Login</h1>
<ul class="d-flex justify-content-center breadcrumb-items">
                <li class="breadcrumb-item"><i class="bi bi-house-door"></i> <a href="@Url.Action("Index","user")">Home</a></li>
<li class="breadcrumb-item active">Login</li>
</ul>
</div>
</div>
</div>


<section class="register-section pt-110">
<div class="container">
<div class="row d-flex justify-content-center text-center">
<div class="col-12">
<div class="register-btn-group">
                    <a href="@Url.Action("Register","user")" class="register-btn style2">Register</a>
                    <a href="@Url.Action("Login","user")" class="login-btn style2">Login</a>
</div>
</div>
</div>
<div class="row gy-4">
<div class="col-lg-6">
<div class="register-left-area style2">
<h3>Hello Again</h3>
<p>Wellcome Back You’ve Been Missed</p>
                    <a href="@Url.Action("Index","user")" class="transparent-btn">Back Home</a>
</div>
</div>
<div class="col-lg-6">
<div class="right-form-area">
<h3>Login Your Account</h3>
                    <form class="w-100" id="loginForm">
                        <div class="form-inner">
                            <label>User Name*</label>
                            <input type="text" id="username" placeholder="User Name">
                        </div>
                        <div class="form-inner">
                            <label>Password *</label>
                            <input type="password" name="password" id="password" placeholder="Password" />
                            <i class="bi bi-eye-slash" id="togglePassword"></i>
                        </div>
                        <div class="form-inner d-flex justify-content-between flex-wrap">
                            <div class="form-group">
                                <input type="checkbox" id="html">
                                <label for="html">I agree to the Terms & Policy</label>
                            </div>
                            <a href="#" class="forgot-pass">Forgotten Password</a>
                        </div>
                        <button type="submit" class="account-btn">LOGIN ACCOUNT</button>
                    </form>
<div class="alternate-signup-box">
<h6>or Sign up WITH</h6>
<div class="btn-group gap-4">
<a href class="google-btn d-flex align-items-center"><i class="bx bxl-google"></i><span>Signup whit google</span></a>
<a href class="facebook-btn d-flex align-items-center"><i class="bx bxl-facebook"></i>Sign up whit facebook</a>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<script>
    document.getElementById("loginForm").addEventListener("submit", function (event) {
        event.preventDefault(); // Prevent the form from submitting

        // Get the values entered by the user
        var username = document.getElementById("username").value;
        var password = document.getElementById("password").value;

        // Check if username and password are correct
        if (username === "admin" && password === "123") {
            // Redirect to the dashboard
            window.location.href = "@Url.Action("Dashboard", "admin")";
        } else {
            // Show an alert if the credentials are incorrect
            alert("Invalid username or password. Please try again.");
        }
    });
</script>